# Generated by Django 4.2.1 on 2023-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='works_full_time',
            field=models.BooleanField(null=True),
        ),
    ]
