# Generated by Django 4.2.1 on 2023-06-02 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_employee_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_level',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
