# Generated by Django 4.2.1 on 2023-06-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_employee_job_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_level',
            field=models.CharField(default='Junior', max_length=20),
        ),
    ]
