# Generated by Django 4.2.1 on 2023-06-03 19:11

from django.db import migrations
from django.utils.text import slugify

from models_demos.web.models import Department


def add_slugs(apps, schema_editor):
    Department = apps.get_model('web', 'Department')

    departments = Department.objects.all()
    for department in Department.objects.all():
        department.slug = slugify(department.name)
        Department.objects.bulk_update(departments, ['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0004_alter_department_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs)
    ]
