# Generated by Django 4.2.1 on 2023-06-02 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_employee_job_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business_account',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
