# Generated by Django 4.2.1 on 2023-06-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_department_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
