# Generated by Django 4.2.1 on 2023-06-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_employee_business_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='business_account',
        ),
    ]
