# Generated by Django 4.2.1 on 2023-06-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_employee_years_of_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullBlankDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank', models.IntegerField(blank=True)),
                ('null', models.IntegerField(null=True)),
                ('blank_null', models.IntegerField(blank=True, null=True)),
                ('default', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.department'),
            preserve_default=False,
        ),
    ]
