# Generated by Django 4.2.1 on 2023-06-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_employee_options_department_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_on',
        ),
    ]
