# Generated by Django 4.2.4 on 2023-08-16 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_image',
            field=models.URLField(verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name'),
        ),
    ]
