# Generated by Django 4.2.4 on 2023-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_eventmodel_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('FESTIVALS', 'Festivals'), ('CONFERENCES', 'Conferences'), ('PERFORMING_ART', 'Performing Art'), ('CONCERTS', 'Concerts'), ('THEME_PARTY', 'Theme Party'), ('OTHER', 'Other')], max_length=14),
        ),
    ]
